### ISSUE TITLE
Better Log abstraction

### ISSUE THREAD

**Issue by pakoito** [team-supercharge/rxsnappy#1]
Consider migrating this unnecessary snippet to something that's more user driven, like SLF4J

https://github.com/team-supercharge/rxsnappy/blob/master/rxsnappy/src/main/java/io/supercharge/rxsnappy/RxSnappyLog.java

**Comment by richardradics** [comment]
Thanks for your feedback!
I think I will remove this class from the project, not really needed.

**Comment by pakoito** [comment]
Fixed on 0.2
