### ISSUE TITLE
Respect the Rx contract for unsubscriptions, make observables lazily evaluated

### ISSUE THREAD

**Issue by pakoito** [team-supercharge/rxsnappy#2]
Using Observable.create() requires respecting several principles about unsubscription and backpressure that this library is not respecting. Apply these principles instead:

https://www.reddit.com/r/androiddev/comments/3u5w0c/if_you_are_writing_observablecreate_theres_a_big/

**Comment by richardradics** [comment]
Thanks for your feedback!
I'm going to start implement this.

**Comment by pakoito** [comment]
Fixed on 0.2
