### ISSUE TITLE
Use a better cache timestamper than new Date()

### ISSUE THREAD

**Issue by pakoito** [team-supercharge/rxsnappy#4]
Use System.getTimeMilliseconds(), unnecessary allocations makes baby jesus weep.

http://stackoverflow.com/questions/368094/system-currenttimemillis-vs-new-date-vs-calendar-getinstance-gettime

**Comment by richardradics** [comment]
Thanks for your feedback!
I'm going to start implement this.

**Comment by pakoito** [comment]
Fixed on 0.2
